version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run: find .
      - run: cd ./src/ArgsToClass.Tests
      - run: dotnet build
      - run: dotnet test --no-build
workflows:
  version: 2
  build_flow:
    jobs:
      - build:
          filters:
            branches:
              only: master
